### ISSUE TITLE
Conjure-up doesn't appear to complete successfully when used in charmbox

### ISSUE THREAD

**Issue by lazypower** [juju-solutions/charmbox#41]
conjure-up is going to continue to gain steam. Charmbox aims to be the defacto resource to go to for a light weight juju test environment. This should be investigated and resolved so we can use charmbox to exercise the conjure-up method of deploying Juju bundles.

@kwmonroe if you get a traceback or additional information we can track can you place it here?

**Comment by kwmonroe** [comment]
Looks like conjure-up is trying to open a unix socket for something:

http://paste.ubuntu.com/20331200/

**Comment by kwmonroe** [comment]
conjure-up wants `/dev/log`.  Containers do not have this socket by default, but we can work around this by creating it in the boot2docker VM and mounting it when charmbox starts.  Here's an example script that i use to start charmbox on OSX:

```
#!/bin/bash

VM_NAME="default"
STATUS=`docker-machine status ${VM_NAME}`

if [[ ${STATUS} != 'Running' ]]; then
  docker-machine start ${VM_NAME}
  docker-machine ssh ${VM_NAME} 'sudo syslogd'
fi

eval $(docker-machine env ${VM_NAME})

docker run -ti --rm --net=bridge \
  -v /dev:/dev \
  -v $JUJU_REPOSITORY:/home/ubuntu/charms \
  -v $JUJU_REPOSITORY/juju-plugins:/home/ubuntu/.juju-plugins \
  -v $JUJU_REPOSITORY/juju2:/home/ubuntu/.local/share/juju \
  jujusolutions/charmbox:devel
```

The `sudo syslogd` creates the socket on the VM and the `-v /dev:/dev` mounts it in the container.  This is enough to get charmbox conjuring.

**Comment by kwmonroe** [comment]
I forgot to put a conclusion in that last post.  This is fixed by either:
- mounting `/dev/log` from the host
- including something that can create a `/dev/log` socket in charmbox

Option 1 is done with the previous example script.. Option 2 is done by including something like `busybox-syslogd` and running `sudo syslogd` in the container each time you need to conjure something.

Option 3 is to adjust conjure-up so it can log to somewhere other than `/dev/log`, but https://github.com/ubuntu/conjure-up/issues/279 would be a better place for that discussion.
